### PR TITLE
Bump to 24.0.2 / update dependencies

### PR DESCRIPTION
**Pull request by mrueg**
# Pull Request

## Description of the change

Bumps to nextcloud 24.0.2
Updates Dependencies 

## Checklist 

- [x] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by tvories** [comment]
Let's bump the chart to a major version.  The last time we upgraded postgres (granted, this is a minor upgrade) it borked people's setup.  This is quite a few version changes, so let's make it a major.

**Comment by mrueg** [comment]
@tvories done :)

**Comment by alesc** [comment]
did you forget bumping values ? 
https://github.com/nextcloud/helm/blob/master/charts/nextcloud/values.yaml#L6

**Comment by mrueg** [comment]
thanks, you are correct. completely forgot this!

**Pull request merged**
