### PR TITLE
Fix #306 (extraVolumeMounts missing from deployment, wrong indent on extraInitContainers)

### LINKED ISSUE #306: extraVolumeMounts missing from deployment, wrong indent on extraInitContainers
Mounting extraVolumeMounts was removed in the 3.2.0 merge (mounts were moved to the helper file).

It also seems like extraInitContainers is indented too much. I'll attach a PR soon

### PR DESCRIPTION
**Pull request by Aste88**
# Pull Request

## Description of the change

Fix #306 :
 - extraVolumeMounts missing from deployment, was removed when moving mount to the helper template
 - wrong indent on extraInitContainers

## Benefits

Fix

## Possible drawbacks

None?

## Applicable issues

- fixes #306

## Checklist 

- [X] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by angelnu** [comment]
This seems to be a (partial) dup from #298 . Merging this would fix #296 .

**Comment by Aste88** [comment]
@tvories done

**Comment by HerHde** [comment]
*Push.*

The broken indentation broke my use-case as well.

**Review by tvories — APPROVED** [review]
lgtm, thanks for the submission!

**Pull request merged**
