### PR TITLE
Bump chart dependencies / nextcloud to 24.0.6 / nextcloud-exporter 0.6.0

### PR DESCRIPTION
**Pull request by mrueg**
# Pull Request

## Description of the change

This will update from redis 6.x to redis 7.0.
Update postgres from 14.x to 15.x
Update nextcloud-exporter to 0.6.0
Update nextcloud to 24.0.7 (latest patch)

## Benefits

Updated dependencies

## Checklist 

- [x] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by mrueg** [comment]
@tvories I've rebased, would you mind taking a look if you got time?

**Comment by mrueg** [comment]
@tvories rebased and bumped to chart version 3.3.0

**Comment by mrueg** [comment]
rebased and updated to 24.0.7 as well as bumped postgresql chart to 12.x (=version 15.0)

**Comment by provokateurin** [comment]
Isn't postgres 15 unsupported right now?

**Pull request closed without merging**
