### PR TITLE
Update values.yaml - Fix cert-manager apiVersion

### PR DESCRIPTION
**Pull request by dharmendrakariya**

### CODE REVIEW

**Comment by tvories** [comment]
Nice catch.  You will need to [bump the chart version](https://github.com/nextcloud/helm/blob/0913ce2f362dbd967cb553146191314f57b9eac9/charts/nextcloud/Chart.yaml#L3) and [sign the DCO](https://github.com/nextcloud/helm/pull/50/checks?check_run_id=1549636415)

**Comment by dharmendrakariya** [comment]
I dont know why but DCO thing is not happening, I tried 2 -3 times, what should I do ?

**Comment by tvories** [comment]
@dharmendrakariya you pushed after ammending the DCO commit?  Also, we will need to bump the chart version to 2.5.4 since we just pushed 2.5.3

**Comment by dharmendrakariya** [comment]
> @dharmendrakariya you pushed after ammending the DCO commit? Also, we will need to bump the chart version to 2.5.4 since we just pushed 2.5.3

Yeah, I think so, will do that tomorrow ✌️

**Comment by dharmendrakariya** [comment]
@tvories hey brother, done, please have a look.

**Comment by tvories** [comment]
Merged!  Thanks @dharmendrakariya

**Pull request merged**
