### PR TITLE
chore: move metrics yaml to extra folder

### PR DESCRIPTION
**Pull request by wrenix**
a first / last try of a really easy reviewable PR

if you see this and need more then 5min ....

@provokateurin 

a split of #481 which is an split of #478  (which does not contain any changes in logic and is 2,5 month old)

### CODE REVIEW

**Comment by provokateurin** [comment]
I understand you are frustrated, but please stay friendly towards others https://nextcloud.com/contribute/code-of-conduct/

**Comment by provokateurin** [comment]
Honestly I'm not sure if this change makes sense. According to https://helm.sh/docs/chart_best_practices/templates/ the current structure is best practice and the page doesn't mention that subdirectories are allowed (but it also doesn't say they are not allowed). https://stackoverflow.com/a/77619725 suggests that it still works, even if it is not documented.

**Comment by wrenix** [comment]
your first link is good, but it does not say anything about, if much of `my-example` exists and nothing about folders inside of templates.

your stackoverflow post, say - that it works (and yes it works also for application charts).

**Review by provokateurin — APPROVED** [review]
Either way, I see that is change makes sense to make the structure less cluttered.

**Comment by wrenix** [comment]
that change does not change any logic -> semver a chore, which does not need a new version, but maybe your ci failed ...

**Comment by provokateurin** [comment]
CI is still running, I'm not sure if it will require a new version :thinking:

**Pull request merged**
