### PR TITLE
Update to 27.0.0

### PR DESCRIPTION
**Pull request by provokateurin**
# Pull Request

## Description of the change

Latest NC version

## Checklist 

- [x] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by provokateurin** [comment]
CI seems to fail because of our new Github runners.

**Comment by provokateurin** [comment]
You don't need to deploy the latest helm chart if you don't want 27. You can also just override the image version instead

**Review by AndyScherzinger — APPROVED** [review]

**Comment by provokateurin** [comment]
@jessebot Your point makes sense, although I would think that semver would always apply to the the chart and not the deployed software. You can use the latest chart and override the image with an old version and it would still work. The update only changes the default version and doesn't introduce breaking changes itself.

To get rid of this problem altogether we could make specifying the image version mandatory. Then we also don't need any updates for new versions. The docker image itself should be already tested by the people who release it. This way we really only care about the chart itself and nothing else. I'm not really a fan of doing this, but it is a possibility.

**Comment by provokateurin** [comment]
Sounds good, I was just playing devil's advocate :D

**Pull request merged**
