### PR TITLE
.github: Update workflows

### PR DESCRIPTION
**Pull request by mrueg**
# Pull Request

## Description of the change

This updates workflows to the latest released github actions.

## Benefits

Updated workflows with less bugs

## Possible drawbacks

Here might be dragons.

## Checklist 

- [x] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).

### CODE REVIEW

**Comment by splitt3r** [comment]
What do you think about adding dependabot to keep the GitHub Actions up to dafe?

**Comment by tvories** [comment]
> 
> 
> What do you think about adding dependabot to keep the GitHub Actions up to date?
> 
> Like: https://github.com/nextcloud/deck/blob/master/.github/dependabot.yml#L42 or https://github.com/nextcloud/.github/blob/master/.github/dependabot.yml

I am up for anything that makes keeping up with dependencies up to date automatically.

**Comment by tvories** [comment]
@mrueg thanks for the submission!

**Comment by mrueg** [comment]
Yeah dependabot or renovate will make sense to add. 

@tvories FWIW I rebased the other two open PRs on this one, hopefully they pass now

**Comment by splitt3r** [comment]
> Yeah dependabot or renovate will make sense to add. @splitt3r do you want to send a PR for that?
> 
> @tvories FWIW I rebased the other two open PRs on this one, hopefully they pass now

Yep 👍🏻

**Pull request merged**
