### PR TITLE
Use external secrets for mariadb-isalive if available.

### LINKED ISSUE #80: mariadb-isalive container stuck with "ERROR 1045 (28000): Access denied for user..."
Hi, I updated the helm chart to 2.5.5 today which led to the following error repeating in the mariadb-isalive container:

`ERROR 1045 (28000): Access denied for user 'nextcloud'@'10.42.0.236' (using password: YES)
waiting for mysql`

Now the DB isn't starting and the pod is stuck in state init 1.

```
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2021-02-16T21:01:20Z'
      message: 'containers with incomplete status: [mariadb-isalive]'
      reason: ContainersNotInitialized
      status: 'False'
      type: Initialized
```

Is there any more data I can provide to help fixing this issue?

### PR DESCRIPTION
**Pull request by hubwoop**
# Pull Request

## Description of the change
Adds logic to use either credentials directly provided via helm chart or secrets referenced by in a k8s-secret for mariadb-isalive init pod.

## Benefits

Fixes #80 

## Possible drawbacks
I hope none.

## Applicable issues

- fixes #80

## Checklist 

- [x] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by hubwoop** [comment]
Is there anything else I can do? Should additional tests that cover the usage of external secrets?

**Comment by tvories** [comment]
> Is there anything else I can do? Should additional tests that cover the usage of external secrets be created?

I'm not sure I understand.  Wouldn't what you wrote handle the case of external secrets being created?

**Comment by hubwoop** [comment]
> 
> 
> > Is there anything else I can do? Should additional tests that cover the usage of external secrets be created?
> 
> I'm not sure I understand. Wouldn't what you wrote handle the case of external secrets being created?

Oh I just wanted to ask whether you would like me to provide a file like [values.yaml](https://github.com/nextcloud/helm/blob/master/charts/nextcloud/values.yaml) with values for testing external secrets via github actions (as seen [here](https://github.com/nextcloud/helm/blob/d71145918af6414823348d17f4a37a6f93df772f/.github/workflows/lint-test.yaml#L33-L37))

**Comment by tvories** [comment]
> Oh I just wanted to ask whether you would like me to provide a file like [values.yaml](https://github.com/nextcloud/helm/blob/master/charts/nextcloud/values.yaml) with values for testing existing secrets via github actions (as seen [here](https://github.com/nextcloud/helm/blob/d71145918af6414823348d17f4a37a6f93df772f/.github/workflows/lint-test.yaml#L33-L37))

I'm not opposed to that, but I'll go ahead and approve this PR so people aren't getting the error

**Comment by tvories** [comment]
Can you bump the chart version to 2.5.8?

**Comment by hubwoop** [comment]
> 
> 
> Can you bump the chart version to 2.5.8?

Done 👍

**Comment by tvories** [comment]
Merged!

**Pull request merged**
