### PR TITLE
bump to nextcloud 24.0.1

### PR DESCRIPTION
**Pull request by varet80**
# Pull Request

## Description of the change

Create an ugprade release for Next cloud24.0.1

## Checklist 

- [ ] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by MichaelSp** [comment]
meanwhile we have ` 24.0.3` .... anyone cares to merge this so we can move on?

**Comment by tvories** [comment]
The PR needs to be revised and conflicts resolved.

**Comment by MichaelSp** [comment]
rebased version: https://github.com/nextcloud/helm/pull/267

**Comment by MichaelSp** [comment]
@tvories thanks for merging my PR #267 ... as result, this can be closed

**Pull request closed without merging**
