### PR TITLE
extraVolumeMounts working again

### LINKED ISSUE #261: Nextcloud pods working, nexctcloud asking to be reistalled
Hi,

I finally found a way to start nextcloud with the helm chart, but it's asking me to be reinstalled (sorry for the italian):

"Sembra che tu stia tentando di reinstallare il tuo Nextcloud. Tuttavia, manca il file CAN_INSTALL dalla cartella config. Crea il file CAN_INSTALL nella cartella config per continuare."

But I should have all of this done with the chart, isn't it?

Here's my config-php:

```
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'overwriteprotocol' => 'https',
  'overwrite.cli.url' => 'https://nextcloud.example.com',
  'filelocking.enabled' => 'true',
  'loglevel' => '2',
  'enable_previews' => true,
  'trusted_domains' =>
  array (
    0 => 'nextcloud',
    1 => 'nextcloud.example.com',
  ),
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'nextcloud-redis-master',
    'port' => '6379',
    'password' => 'nextcloud-admin',
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'smtp.example.com',
  'mail_smtpport' => '587',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => true,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => 'nextcloud@example.com',
  'mail_smtppassword' => 'password',
  'mail_from_address' => 'nextcloud',
  'mail_domain' => 'example.com',
  'passwordsalt' => 'passwordsalt',
  'secret' => 'secret',
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '24.0.2.1',
  'dbname' => 'nextcloud',
  'dbhost' => 'nextcloud-mariadb',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'dbuser',
  'dbpassword' => 'dbpassword',
  'instanceid' => 'instanceid',
);
```

### LINKED ISSUE #296: extraVolumeMounts not working in 3.2.0
Due to https://github.com/nextcloud/helm/commit/1fee95ac23e2a9b1a4568b9444eaa88ef749c422 the `extraVolumeMounts` is ignored. It is missing at https://github.com/nextcloud/helm/blob/1fee95ac23e2a9b1a4568b9444eaa88ef749c422/charts/nextcloud/templates/_helpers.tpl#L210

### PR DESCRIPTION
**Pull request by angelnu**
# Pull Request

## Description of the change

Fixes #296 

## Benefits

extraVolumeMounts working again.

## Possible drawbacks
NA

## Applicable issues

- fixes #296 

## Additional information

NA

## Checklist 

- [x] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by jld3103** [comment]
Why does it also fix https://github.com/nextcloud/helm/issues/261 ?

**Comment by angelnu** [comment]
It does not - it fixes only #296 Will change.

**Comment by angelnu** [comment]
Thanks!

**Comment by angelnu** [comment]
@tvories - soory but my fix was not right - see #313

**Pull request merged**
