### PR TITLE
Update nextcloud-exporter to 0.4.0

### PR DESCRIPTION
**Pull request by mrueg**
# Pull Request

## Description of the change

https://github.com/xperimental/nextcloud-exporter/compare/v0.3.0...v0.4.0

## Possible drawbacks

-

## Applicable issues

-
## Additional information

-

## Checklist 

- [x] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by mrueg** [comment]
@tvories  can you help out and take a look here please? Thanks!

**Comment by mrueg** [comment]
@tvories thanks for the merge of #131 rebased this onto latest master

**Comment by mrueg** [comment]
Not sure why the workflow failed, I repushed again

**Comment by tvories** [comment]
@mrueg we'll have to bump the version on this one since I used 2.7.1 on #133

**Comment by mrueg** [comment]
@tvories done! Thanks for the merge

**Comment by mrueg** [comment]
before you merge this change, I need to provide a fix for https://github.com/nextcloud/helm/runs/3247028809#step:7:12 seems like the release action needs more info.

**Pull request merged**
