### PR TITLE
Update to nextcloud 21 and dependency charts

### PR DESCRIPTION
**Pull request by mrueg**
# Pull Request

## Description of the change

This updates the nextcloud image to nextcloud 21 and dependency charts to its latest version.

## Applicable issues

- fixes #

## Checklist 

- [x] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by tvories** [comment]
There is a lot going on here that would be good to look over a bit.  You have changed more than the dependency charts.  You've changed the way auth works with the database (or at least renamed the params) and I think that warrants some thought.  I'm not sure when I'll have some time to look over this, but I'll try to get this approved sometime.

**Comment by mrueg** [comment]
@tvories I can split it up into smaller changes if that's better and easier to review

**Comment by tvories** [comment]
Yeah, I could easily approve a dependency update and then we could open a separate PR to discuss changing the auth configuration

**Comment by mrueg** [comment]
@tvories I only applied the chart changes that don't require a larger change to the values file structure.

**Comment by tvories** [comment]
@mrueg thanks for that!  I really appreciate the submissions.

**Pull request merged**
