### PR TITLE
Upgrade to 26.0.2

### PR DESCRIPTION
**Pull request by pfuhrmann**
# Pull Request

## Description of the change

New Nextcloud version.

## Checklist

- [x] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] (optional) Variables are documented in the README.md

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]

**Comment by pfuhrmann** [comment]
Seems the image is not available yet. I thought they release it at the same time, seems not.

**Comment by provokateurin** [comment]
Yeah we always have to wait for https://github.com/nextcloud/docker to pick it up.

**Comment by pfuhrmann** [comment]
I nudged them in https://github.com/nextcloud/docker/issues/1997, let's see :crossed_fingers:

**Comment by pfuhrmann** [comment]
The image is available now [1]. cc @provokateurin can we somehow re-run CI?

[1] https://hub.docker.com/layers/library/nextcloud/26.0.2/images/sha256-69c8f46e049e72d8433e2ec4a59589aa6296c84d09b3dbcac8c16906a2bf6d4c?context=explore

**Pull request merged**
