### PR TITLE
Removed duplicate service account definitions in the deployment

### PR DESCRIPTION
**Pull request by Xartos**
# Pull Request

## Description of the change

Removed some duplicate definitions of the service account in the deployment.
Guessing they came from some merge or something.

## Benefits

No real benefits since the chart works even with these multiple definitions.
I guess more nicer looking code (manifests) is the benefit :slightly_smiling_face: 

## Possible drawbacks

None

## Applicable issues

- fixes #

## Checklist 

- [x] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by mrueg** [comment]
There is already an open PR here https://github.com/nextcloud/helm/pull/121 maybe you can work with the author of this PR  to get it fixed?

**Comment by Xartos** [comment]
@mrueg Aah, didn't see that one but yea that makes sense! Thanks

**Comment by mrueg** [comment]
@Xartos maybe my message was bit ambiguous. Feel free to take that commit and bump the chart version, after a second look, I believe the PR went stale. :)

**Comment by Xartos** [comment]
@mrueg Maybe it was your link that nudged it and woke it up, because it's now merged :slightly_smiling_face:

**Pull request closed without merging**
