### PR TITLE
chore: replace if with with (and improve strip using with -)

### PR DESCRIPTION
**Pull request by wrenix**
# Pull Request

## Checklist 

- [x] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] (optional) Variables are documented in the README.md

### CODE REVIEW

**Review by provokateurin — COMMENTED** [review]
LGTM, but I think in a few places nindent is used where indent would be enough. Could you fix that?

**Comment by wrenix** [comment]
I am a hours away from keyboard, sry -> i believe there is needed, but i take a look

**Comment by wrenix** [comment]
you are correct, if i would not use in some places `{{- toYaml`, i could use `indent` instatt of `nindent`.
I often use it together with `{{- with` and {{- end`. so it looks for me nice on writing and reading.

that is a kind of personal preference. should i change it?

**Comment by provokateurin** [comment]
I  see, that makes sense. Then I prefer this style :) Still, it would be great to have a tool to enforce the style.

**Comment by wrenix** [comment]
increase chart-version after rebase

**Review by provokateurin — APPROVED** [review]

**Pull request merged**
