### PR TITLE
Adapt chart to work with official nextcloud fpm docker image

### PR DESCRIPTION
**Pull request by claudiuvintila**
# Pull Request

## Applicable issues

- fixes #

## Checklist 

- [x] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by claudiuvintila** [comment]
Adapt chart to work with official nextcloud fpm docker image

**Comment by provokateurin** [comment]
The fpm image works just fine, seems like you have a problem in your setup?

**Comment by claudiuvintila** [comment]
Those are the things I had to change in order for the chart to work with nextcloud:25.0.4-fpm docker image

**Comment by claudiuvintila** [comment]
The fsGroup used was blocking the fpm from starting. Also added some parameters for the ports as they are hardcoded.

**Pull request closed without merging**
