### PR TITLE
docs: fix typo in s3 config

### PR DESCRIPTION
**Pull request by wagoid**
## Description of the change

Hi there! I found this small typo in the docs.

## Checklist 

- [X] I have read the [CONTRIBUTING.md](https://github.com/nextcloud/helm/blob/main/CONTRIBUTING.md#pull-requests) doc.
- [X] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] (optional) Parameters are documented in the README.md

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]

**Comment by provokateurin** [comment]
The DCO is missing

**Comment by wagoid** [comment]
DCO fixed :heavy_check_mark:

**Comment by wagoid** [comment]
@provokateurin I needed to force push to fix DCO, could you approve the new workflow runs? :pray:

**Comment by provokateurin** [comment]
Ah only saw it now. The new Github merge UI doesn't show that the workflows need to be approved so I thought they were just waiting for a runner to pick them up.

**Pull request merged**
